# For simplicity – mailer bundle dropped mailer_user parameter after Symfony 3 -> Symfony 4
parameters:
    mailer_user: "no-replay@nfqakademija.lt"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
